name: Build and push to NuGet

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore -r linux-x64 GrillBot.Core/
      - name: Build as Debug
        run: dotnet build -c Debug -r linux-x64 --no-self-contained --no-restore GrillBot.Core/
      - name: Build as Release
        run: dotnet build -c Release -r linux-x64 --no-self-contained --no-restore GrillBot.Core/
  PublishToNuGet:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/master'
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          source-url: https://nuget.pkg.github.com/GrillBot/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: dotnet restore -r linux-x64 GrillBot.Core/
      - name: Build
        run: dotnet build -c Release -r linux-x64 --no-self-contained --no-restore GrillBot.Core/
      - name: Create the package
        run: dotnet pack -c Release GrillBot.Core/
      - name: Publish the package to GPR
        run: dotnet nuget push GrillBot.Core/bin/Release/*.nupkg --skip-duplicate
        
      
      
